# This file created by conda-build 25.5.0
# ------------------------------------------------

package:
  name: vc14_runtime
  version: 14.44.35208
source:
  - url: https://download.visualstudio.microsoft.com/download/pr/40b59c73-1480-4caf-ab5b-4886f176bf71/D62841375B90782B1829483AC75695CCEF680A8F13E7DE569B992EF33C6CD14A/vc_redist.x64.exe
    sha256: d62841375b90782b1829483ac75695ccef680a8f13e7de569b992ef33c6cd14a
build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  no_link:
    - Library/bin/*.dll
  missing_dso_whitelist:
    - '*.DLL'
    - '*.dll'
  number: 10
  string: h4927774_10
requirements:
  build:
    - m2-bash 4.3.042 5
    - m2-gcc-libs 5.3.0 4
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-p7zip 9.38.1 2
    - msys2-conda-epoch 20160418 1
  run:
    - ucrt >=10.0.20348.0
  run_constrained:
    - vs2015_runtime 14.44.35208.* *_10
test:
  commands:
    - dir %PREFIX%\\Library\\bin\\*.dll
    - if not exist %LIBRARY_BIN%\api-ms-win-core-console-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-console-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-datetime-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-datetime-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-debug-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-debug-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-errorhandling-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-errorhandling-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-file-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-file-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-file-l1-2-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-file-l1-2-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-file-l2-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-file-l2-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-handle-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-handle-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-heap-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-heap-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-interlocked-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-interlocked-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-libraryloader-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-libraryloader-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-localization-l1-2-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-localization-l1-2-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-memory-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-memory-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-namedpipe-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-namedpipe-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-processenvironment-l1-1-0.dll exit
      1
    - if not exist %PREFIX%\api-ms-win-core-processenvironment-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-processthreads-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-processthreads-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-processthreads-l1-1-1.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-processthreads-l1-1-1.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-profile-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-profile-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-rtlsupport-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-rtlsupport-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-string-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-string-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-synch-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-synch-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-synch-l1-2-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-synch-l1-2-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-sysinfo-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-sysinfo-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-timezone-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-timezone-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-core-util-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-core-util-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-crt-conio-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-crt-conio-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-crt-convert-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-crt-convert-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-crt-environment-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-crt-environment-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-crt-filesystem-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-crt-filesystem-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-crt-heap-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-crt-heap-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-crt-locale-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-crt-locale-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-crt-math-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-crt-math-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-crt-multibyte-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-crt-multibyte-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-crt-private-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-crt-private-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-crt-process-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-crt-process-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-crt-runtime-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-crt-runtime-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-crt-stdio-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-crt-stdio-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-crt-string-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-crt-string-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-crt-time-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-crt-time-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\api-ms-win-crt-utility-l1-1-0.dll exit 1
    - if not exist %PREFIX%\api-ms-win-crt-utility-l1-1-0.dll exit 1
    - if not exist %LIBRARY_BIN%\concrt140.dll exit 1
    - if not exist %PREFIX%\concrt140.dll exit 1
    - if not exist %LIBRARY_BIN%\msvcp140_1.dll exit 1
    - if not exist %PREFIX%\msvcp140_1.dll exit 1
    - if not exist %LIBRARY_BIN%\msvcp140_2.dll exit 1
    - if not exist %PREFIX%\msvcp140_2.dll exit 1
    - if not exist %LIBRARY_BIN%\msvcp140.dll exit 1
    - if not exist %PREFIX%\msvcp140.dll exit 1
    - if not exist %LIBRARY_BIN%\ucrtbase.dll exit 1
    - if not exist %PREFIX%\ucrtbase.dll exit 1
    - if not exist %LIBRARY_BIN%\vcamp140.dll exit 1
    - if not exist %PREFIX%\vcamp140.dll exit 1
    - if not exist %LIBRARY_BIN%\vccorlib140.dll exit 1
    - if not exist %PREFIX%\vccorlib140.dll exit 1
    - if not exist %LIBRARY_BIN%\vcomp140.dll exit 1
    - if not exist %PREFIX%\vcomp140.dll exit 1
    - if not exist %LIBRARY_BIN%\vcruntime140.dll exit 1
    - if not exist %PREFIX%\vcruntime140.dll exit 1
    - if not exist %LIBRARY_BIN%\msvcp140_atomic_wait.dll exit 1
    - if not exist %PREFIX%\msvcp140_atomic_wait.dll exit 1
    - if not exist %LIBRARY_BIN%\msvcp140_codecvt_ids.dll exit 1
    - if not exist %PREFIX%\msvcp140_codecvt_ids.dll exit 1
    - if not exist %LIBRARY_BIN%\vcruntime140_1.dll exit 1
    - if not exist %PREFIX%\vcruntime140_1.dll exit 1
    - if not exist %LIBRARY_BIN%\vcruntime140_threads.dll exit 1
    - if not exist %PREFIX%\vcruntime140_threads.dll exit 1
about:
  summary: MSVC runtimes associated with cl.exe version 19.44.35207 (VS 2022 update
    14)
  home: https://visualstudio.microsoft.com/downloads/
  license: LicenseRef-MicrosoftVisualCpp2015-2022Runtime
  license_family: Proprietary
  license_file:
    - LICENSE.RTF
    - LICENSE.TXT
extra:
  feedstock-name: vc
  recipe-maintainers:
    - 183amir
    - isuruf
    - jakirkham
    - msarahan
    - patricksnape
    - pelson
  final: true
  copy_test_source_files: true
  sha: f2304a1a86c2d8665c55c3f532dc4d1713ef81ef
  remote_url: git@github.com:AnacondaRecipes/vc-feedstock.git
  flow_run_id: 34be99fa-3404-4ca1-92c5-120797a7aaa3
