# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Thu Jun 27 04:34:51 2024
# ------------------------------------------------

package:
  name: krb5
  version: 1.21.3
source:
  sha256: 2157d92020d408ed63ebcd886a92d1346a1383b0f91123a0473b4f69b4a24861
  url: https://github.com/krb5/krb5/archive/krb5-1.21.3-final.tar.gz
build:
  number: '0'
  run_exports:
    - krb5 >=1.21.3,<1.22.0a0
  string: hdf4eb48_0
requirements:
  build:
    - gettext 0.22.5 h5728263_2
    - gettext-tools 0.22.5 h7d00a51_2
    - libasprintf 0.22.5 h5728263_2
    - libasprintf-devel 0.22.5 h5728263_2
    - libgettextpo 0.22.5 h5728263_2
    - libgettextpo-devel 0.22.5 h5728263_2
    - libiconv 1.17 hcfcfb64_2
    - libintl 0.22.5 h5728263_2
    - libintl-devel 0.22.5 h5728263_2
    - m2-base 1.0.0 2
    - m2-bash 4.3.042 5
    - m2-bash-completion 2.3 2
    - m2-catgets 1.1 3
    - m2-coreutils 8.25 102
    - m2-dash 0.5.8 2
    - m2-diffutils 3.3 4
    - m2-file 5.25 2
    - m2-filesystem 2016.04 4
    - m2-findutils 4.6.0 2
    - m2-gawk 4.1.3 2
    - m2-gcc-libs 5.3.0 4
    - m2-gettext 0.19.7 4
    - m2-gmp 6.1.0 3
    - m2-grep 2.22 4
    - m2-gzip 1.7 2
    - m2-inetutils 1.9.2 2
    - m2-info 6.0 2
    - m2-less 481 2
    - m2-libasprintf 0.19.7 4
    - m2-libbz2 1.0.6 3
    - m2-libcatgets 1.1 3
    - m2-libcrypt 1.3 2
    - m2-libgettextpo 0.19.7 4
    - m2-libiconv 1.14 3
    - m2-libintl 0.19.7 4
    - m2-liblzma 5.2.2 2
    - m2-libpcre 8.38 2
    - m2-libreadline 6.3.008 8
    - m2-libutil-linux 2.26.2 2
    - m2-libxml2 2.9.2 3
    - m2-make 4.1 5
    - m2-mintty 1!2.2.3 2
    - m2-mpfr 3.1.4 2
    - m2-msys2-launcher-git 0.3.28.860c495 2
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-ncurses 6.0.20160220 2
    - m2-sed 4.2.2 3
    - m2-tar 1.28 4
    - m2-tftp-hpa 5.2 2
    - m2-time 1.7 2
    - m2-ttyrec 1.0.8 2
    - m2-tzcode 2015.e 2
    - m2-unzip 6.0 3
    - m2-util-linux 2.26.2 2
    - m2-which 2.21 3
    - m2-zip 3.0 2
    - m2-zlib 1.2.8 4
    - msys2-conda-epoch 20160418 1
    - perl 5.32.1.1 7_h57928b3_strawberry
    - posix 1.0.0 2
    - ucrt 10.0.22621.0 h57928b3_0
    - vc 14.3 h8a93ad2_20
    - vc14_runtime 14.40.33810 ha82c5b3_20
    - vs2019_win-64 19.29.30139 he1865b1_20
    - vs_win-64 2019.11 he1865b1_20
    - vswhere 3.1.7 h57928b3_0
  host:
    - ca-certificates 2024.6.2 h56e8100_0
    - openssl 3.3.1 h2466b09_1
    - ucrt 10.0.22621.0 h57928b3_0
    - vc 14.3 h8a93ad2_20
    - vc14_runtime 14.40.33810 ha82c5b3_20
  run:
    - openssl >=3.3.1,<4.0a0
    - ucrt >=10.0.20348.0
    - vc >=14.2,<15
    - vc14_runtime >=14.29.30139
test:
  commands:
    - if not exist %LIBRARY_BIN%\krb5_64.dll exit 1
about:
  home: http://web.mit.edu/kerberos/
  license: MIT
  license_file: doc/notice.rst
  summary: A network authentication protocol.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240627.1.1
  recipe-maintainers:
    - mariusvniekerk
    - mingwandroid
    - ocefpaf
    - pelson
    - wolfv
  remote_url: https://github.com/conda-forge/krb5-feedstock
  sha: 23ac81ca671fccb138f6ae25cfab72c15b29f6b0
