schema_version: 1

context:
  version: 311

package:
  name: pywin32
  version: ${{ version }}

source:
  url: https://github.com/mhammond/pywin32/archive/b${{ version }}.tar.gz
  sha256: 4ae3f0d4adacc331733fe1204f7f93b8654615ca325adfc9eb6c67198246a91b
  patches:
    - 0003-remove-PATH-pth-hack.patch
    - do-not-build-scintilla.patch

build:
  number: 0

requirements:
  build:
    - if: win and python_impl != 'pypy'
      then:
        - ${{ compiler("c") }}
        - ${{ stdlib("c") }}
        - ${{ compiler("cxx") }}
  host:
    - python
    - if: win and python_impl != 'pypy'
      then:
        - pip
        - setuptools
  run:
    - python

tests:
  - requirements:
      run:
        - python
    script: run_test.py

about:
  license: PSF-2.0
  license_file: Pythonwin/License.txt
  summary: Python extensions for Windows
  description: |
    A set of extension modules that provides access to many of the Windows API functions.
  homepage: https://github.com/mhammond/pywin32
  repository: https://github.com/mhammond/pywin32

extra:
  recipe-maintainers:
    - mingwandroid
    - nicoddemus
    - carlodri
    - xhochy
