# This file created by conda-build 25.3.1
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Tue Apr  1 04:51:52 2025
# ------------------------------------------------

package:
  name: python_abi
  version: '3.10'
build:
  number: '6'
  string: 6_cp310
  track_features: null
requirements:
  build: []
  run: []
  run_constrained:
    - python 3.10.* *_cpython
test:
  commands:
    - echo "hello"
about:
  home: https://github.com/conda-forge/python_abi-feedstock
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Metapackage to select python implementation
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250401.4.1
  recipe-maintainers:
    - chrisburr
    - isuruf
  remote_url: https://github.com/conda-forge/python_abi-feedstock
  sha: 49ae25b8dcd21b2f2da9bb22a28f47b8d00136b5
