# This file created by conda-build 25.3.2
# meta.yaml template originally from:
# C:\b\abs_58a5guh8bt\clone\recipe, last modified Mon Apr 14 20:43:40 2025
# ------------------------------------------------

package:
  name: expat
  version: 2.7.1
source:
  sha256: 45c98ae1e9b5127325d25186cf8c511fa814078e9efeae7987a574b482b79b3d
  url: https://github.com/libexpat/libexpat/releases/download/R_2_7_1/expat-2.7.1.tar.bz2
build:
  number: '0'
  run_exports:
    - expat >=2.7.1,<3.0a0
  string: h8ddb27b_0
requirements:
  build:
    - bzip2 1.0.8 h2bbff1b_6
    - cmake 3.31.2 h53b1909_0
    - libuv 1.48.0 h827c3e9_0
    - lz4-c 1.9.4 h2bbff1b_1
    - vc 14.42 haa95532_4
    - vs2015_runtime 14.42.34433 he0abc0d_4
    - vs2019_win-64 19.29.30154 h96f319f_7
    - vswhere 2.8.4 haa95532_0
    - xz 5.6.4 h4754444_1
    - zlib 1.2.13 h8cc25b3_1
    - zstd 1.5.6 h8880b57_0
  host:
    - vc 14.42 haa95532_4
    - vs2015_runtime 14.42.34433 he0abc0d_4
  run:
    - vc >=14.2,<15.0a0
    - vs2015_runtime >=14.29.30133,<15.0a0
test:
  commands:
    - xmlwf -h
about:
  description: 'Expat is a stream-oriented XML parser library written in C.

    Expat excels with files too large to fit RAM, and where performance

    and flexibility are crucial.

    '
  dev_url: https://github.com/libexpat/libexpat
  doc_url: https://libexpat.github.io/doc/
  home: https://libexpat.github.io
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Expat XML parser library in C
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 584cf770-eb7f-4bc6-b4c2-5e8a871fb9f9
  recipe-maintainers:
    - kwilcox
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/expat-feedstock.git
  sha: 940d4c718f0f9ef985be1361a366fe750dfc03a8
