# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Dec  3 13:07:38 2024
# ------------------------------------------------

package:
  name: wcwidth
  version: 0.2.13
source:
  sha256: 72ea0c06399eb286d978fdedb6923a9eb47e1c486ce63e9b4e64fc18303972b5
  url: https://pypi.org/packages/source/w/wcwidth/wcwidth-0.2.13.tar.gz
build:
  noarch: python
  number: '1'
  script: /home/conda/feedstock_root/build_artifacts/wcwidth_1733231326287/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: pyhd8ed1ab_1
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.8.30 hbcca054_0
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.47.0 hadc24fc_1
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - openssl 3.4.0 hb9d3cd8_0
    - pip 24.3.1 pyh8b19718_0
    - python 3.9.20 h13acc7a_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 75.6.0 pyhff2d567_1
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024b hc8b5060_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.9
test:
  commands:
    - pip check
  imports:
    - wcwidth
  requires:
    - pip
    - python 3.9.*
about:
  home: https://github.com/jquast/wcwidth
  license: MIT
  license_file: LICENSE
  summary: Measures number of Terminal column cells of wide-character codes.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241203.3.1
  recipe-maintainers:
    - ocefpaf
  remote_url: https://github.com/conda-forge/wcwidth-feedstock
  sha: 52b5a153b6927f022d9e1a419d05f0b9814eda3b
