CI: azure
CONDA_BUILD_SKIP_TESTS: ''
bzip2: '1'
c_compiler: vs2019
c_stdlib: vs
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: vs2019
expat: '2'
extend_keys:
- pin_run_as_build
- extend_keys
- ignore_build_only_deps
- ignore_version
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
is_python_min: 'no'
liblzma_devel: '5'
lua: '5'
numpy: '1.16'
openssl: '3'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
python: '3.10'
python_impl: cpython
r_base: '3.4'
sqlite: '3'
target_platform: win-64
tk: '8.6'
vc: '14'
zlib: '1'
