# This file created by conda-build 3.21.5
# meta.yaml template originally from:
# C:\ci\containers\00001p9pbu5\tmp\build\80754af9\combined_recipe, last modified Mon Oct 25 22:48:27 2021
# ------------------------------------------------

package:
  name: ca-certificates
  version: 2021.10.26
source:
  fn: cacert.pem
  sha256: ae31ecb3c6e9ff3154cb7a55f017090448f88482f0e94ac927c0c67a1f33b9cf
  url: https://curl.haxx.se/ca/cacert-2021-10-26.pem
build:
  commands:
    - /usr/bin/curl --cacert %LIBRARY_PREFIX%\\ssl\\cacert.pem https://www.google.com
    - if not exist %LIBRARY_PREFIX%\\ssl\\cacert.pem exit 1
    - if not exist %LIBRARY_PREFIX%\\ssl\\cert.pem exit 1
  number: '2'
  string: haa95532_2
requirements:
  build: []
  run: []
about:
  home: https://github.com/conda-forge/ca-certificates-feedstock
  license: MPL 2.0
  license_file: LICENSE.txt
  summary: Certificates for use with other packages.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
