# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Thu Nov 14 11:40:23 2024
# ------------------------------------------------

package:
  name: zeromq
  version: 4.3.5
source:
  fn: zeromq-4.3.5.tar.gz
  patches:
    - 001-windows-install.patch
    - 003-no-stdc++-on-win.patch
    - pr4663.patch
    - pr4684.patch
  sha256: 6653ef5910f17954861fe72332e68b03ca6e4d9c7160eb3a8de5a5a913bfab43
  url: https://github.com/zeromq/libzmq/releases/download/v4.3.5/zeromq-4.3.5.tar.gz
build:
  number: '7'
  run_exports:
    - zeromq >=4.3.5,<4.3.6.0a0
  string: ha9f60a1_7
requirements:
  build:
    - bzip2 1.0.8 h2466b09_7
    - ca-certificates 2024.8.30 h56e8100_0
    - cmake 3.30.5 h400e5d1_0
    - krb5 1.21.3 hdf4eb48_0
    - libcurl 8.10.1 h1ee3ff0_0
    - libexpat 2.6.4 he0c23c2_0
    - libssh2 1.11.0 h7dfc565_0
    - libuv 1.49.2 h2466b09_0
    - libzlib 1.3.1 h2466b09_2
    - openssl 3.4.0 h2466b09_0
    - ucrt 10.0.22621.0 h57928b3_1
    - vc 14.3 h8a93ad2_22
    - vc14_runtime 14.40.33810 hcc2c482_22
    - vs2015_runtime 14.40.33810 h3bf8584_22
    - vs2019_win-64 19.29.30139 he1865b1_22
    - vs_win-64 2019.11 he1865b1_22
    - vswhere 3.1.7 h57928b3_0
    - xz 5.2.6 h8d14728_0
    - zstd 1.5.6 h0ea2cb4_0
  host:
    - ca-certificates 2024.8.30 h56e8100_0
    - krb5 1.21.3 hdf4eb48_0
    - libsodium 1.0.20 hc70643c_0
    - openssl 3.4.0 h2466b09_0
    - ucrt 10.0.22621.0 h57928b3_1
    - vc 14.3 h8a93ad2_22
    - vc14_runtime 14.40.33810 hcc2c482_22
  run:
    - krb5 >=1.21.3,<1.22.0a0
    - libsodium >=1.0.20,<1.0.21.0a0
    - ucrt >=10.0.20348.0
    - vc >=14.2,<15
    - vc14_runtime >=14.29.30139
about:
  home: http://zeromq.org
  license: MPL-2.0
  license_file: LICENSE
  summary: A high-performance asynchronous messaging library.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241114.1.1
  recipe-maintainers:
    - JohanMabille
    - SylvainCorlay
    - davidbrochart
    - jakirkham
    - minrk
  remote_url: https://github.com/conda-forge/zeromq-feedstock
  sha: 2a3c78c24ee9f87bcc58972bad719232d7b432e5
