# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: zlib
  version: 1.3.1
source:
  sha256: 9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23
  url:
    - http://zlib.net/zlib-1.3.1.tar.gz
    - https://gnupg.org/ftp/gcrypt/zlib/zlib-1.3.1.tar.gz
build:
  number: 2
  run_exports:
    - libzlib >=1.3.1,<2.0a0
  string: h2466b09_2
requirements:
  build:
    - vs2019_win-64 19.29.30139 he1865b1_21
    - vs_win-64 2019.11 he1865b1_21
    - vswhere 3.1.7 h57928b3_0
  host:
    - libzlib 1.3.1 h2466b09_2
    - ucrt 10.0.22621.0 h57928b3_0
    - vc 14.3 h8a93ad2_21
    - vc14_runtime 14.40.33810 ha82c5b3_21
  run:
    - libzlib 1.3.1 h2466b09_2
    - ucrt >=10.0.20348.0
    - vc >=14.2,<15
    - vc14_runtime >=14.29.30139
test:
  commands:
    - if not exist %LIBRARY_LIB%\zlibstatic.lib exit 1
    - if not exist %LIBRARY_LIB%\zlib.lib exit 1
    - if not exist %LIBRARY_LIB%\pkgconfig\zlib.pc exit 1
    - if not exist %LIBRARY_INC%\zlib.h exit 1
    - if exist %LIBRARY_LIB%\zlibwapi.lib exit 1
    - call test_compile_flags.bat
  files:
    - test_compile_flags.bat
    - test_compile_flags.c
  requires:
    - vs2019_win-64
about:
  description: 'zlib is designed to be a free, general-purpose, lossless data-compression

    library for use on virtually any computer hardware and operating system.

    '
  dev_url: https://github.com/madler/zlib
  doc_url: http://zlib.net/manual.html
  home: http://zlib.net/
  license: Zlib
  license_family: Other
  license_file: LICENSE
  summary: Massively spiffy yet delicately unobtrusive compression library
extra:
  copy_test_source_files: true
  feedstock-name: zlib
  final: true
  flow_run_id: azure_20241003.7.1
  recipe-maintainers:
    - groutr
    - isuruf
    - msarahan
    - ocefpaf
  remote_url: https://github.com/conda-forge/zlib-feedstock
  sha: 4be6236771d0a41a143f5947933e13e1ab7db35a
