# This file created by conda-build 25.5.0
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Sat Jun 14 10:52:53 2025
# ------------------------------------------------

package:
  name: pyzmq
  version: 27.0.0
source:
  url: https://pypi.org/packages/source/p/pyzmq/pyzmq-27.0.0.tar.gz
  sha256: b1f08eeb9ce1510e6939b6e5dcd46a17765e2333daae78ecf4606808442e52cf
build:
  number: '0'
  string: py310h656833d_0
requirements:
  build:
    - bzip2 1.0.8 h2466b09_7
    - ca-certificates 2025.4.26 h4c7d964_0
    - cmake 4.0.3 hff78f93_0
    - krb5 1.21.3 hdf4eb48_0
    - libcurl 8.14.1 h88aaa65_0
    - libexpat 2.7.0 he0c23c2_0
    - liblzma 5.8.1 h2466b09_2
    - libssh2 1.11.1 h9aa295b_0
    - libuv 1.51.0 h2466b09_0
    - libzlib 1.3.1 h2466b09_2
    - openssl 3.5.0 ha4e3fda_1
    - ucrt 10.0.22621.0 h57928b3_1
    - vc 14.3 h2b53caa_26
    - vc14_runtime 14.42.34438 hfd919c2_26
    - vs2019_win-64 19.29.30139 h7dcff83_26
    - vs_win-64 2019.11 h7dcff83_26
    - vswhere 3.1.7 h40126e0_1
    - zstd 1.5.7 hbeecb71_2
  host:
    - bzip2 1.0.8 h2466b09_7
    - ca-certificates 2025.4.26 h4c7d964_0
    - cython 3.1.2 py310h6bd2d47_2
    - exceptiongroup 1.3.0 pyhd8ed1ab_0
    - importlib-metadata 8.7.0 pyhe01879c_1
    - importlib-resources 6.5.2 pyhd8ed1ab_0
    - importlib_resources 6.5.2 pyhd8ed1ab_0
    - krb5 1.21.3 hdf4eb48_0
    - libexpat 2.7.0 he0c23c2_0
    - libffi 3.4.6 h537db12_1
    - liblzma 5.8.1 h2466b09_2
    - libsodium 1.0.20 hc70643c_0
    - libsqlite 3.50.1 h67fdade_0
    - libzlib 1.3.1 h2466b09_2
    - openssl 3.5.0 ha4e3fda_1
    - packaging 25.0 pyh29332c3_1
    - pathspec 0.12.1 pyhd8ed1ab_1
    - pip 25.1.1 pyh8b19718_0
    - python 3.10.18 h8c5b53a_0_cpython
    - python_abi 3.10 7_cp310
    - scikit-build-core 0.11.4 pyh520c2d9_0
    - setuptools 80.9.0 pyhff2d567_0
    - tk 8.6.13 h2c6b04d_2
    - tomli 2.2.1 pyhd8ed1ab_1
    - typing-extensions 4.14.0 h32cad80_0
    - typing_extensions 4.14.0 pyhe01879c_0
    - tzdata 2025b h78e105d_0
    - ucrt 10.0.22621.0 h57928b3_1
    - vc 14.3 h2b53caa_26
    - vc14_runtime 14.42.34438 hfd919c2_26
    - wheel 0.45.1 pyhd8ed1ab_1
    - zeromq 4.3.5 ha9f60a1_7
    - zipp 3.23.0 pyhd8ed1ab_0
  run:
    - libsodium >=1.0.20,<1.0.21.0a0
    - python >=3.10,<3.11.0a0
    - python_abi 3.10.* *_cp310
    - ucrt >=10.0.20348.0
    - vc >=14.2,<15
    - vc14_runtime >=14.29.30139
    - zeromq >=4.3.5,<4.3.6.0a0
test:
  source_files:
    - pyproject.toml
    - pytest.ini
    - tests
  imports:
    - zmq
    - zmq.backend.cython
    - zmq.devices.monitoredqueue
  requires:
    - pip
    - pytest
  commands:
    - pip check
about:
  home: https://github.com/zeromq/pyzmq
  summary: Python bindings for zeromq
  license: BSD-3-Clause
  license_file:
    - LICENSE.md
extra:
  recipe-maintainers:
    - JohanMabille
    - SylvainCorlay
    - jakirkham
    - jan-janssen
    - minrk
    - msarahan
    - ocefpaf
    - pelson
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250614.2.1
  remote_url: https://github.com/conda-forge/pyzmq-feedstock
  sha: 055fe932af923c4168a1c67f72e4e3834072f4ba
