# This file created by conda-build 25.5.0
# ------------------------------------------------

package:
  name: expat
  version: 2.7.1
source:
  url: https://github.com/libexpat/libexpat/releases/download/R_2_7_1/expat-2.7.1.tar.bz2
  sha256: 45c98ae1e9b5127325d25186cf8c511fa814078e9efeae7987a574b482b79b3d
build:
  run_exports:
    - libexpat >=2.7.1,<3.0a0
  ignore_run_exports_from:
    - vs2022_win-64
  number: 0
  string: hac47afa_0
requirements:
  build:
    - cmake-no-system 4.0.3 he0c23c2_0
    - ucrt 10.0.22621.0 h57928b3_1
    - vc 14.3 h41ae7f8_26
    - vc14_runtime 14.44.35208 h818238b_26
    - vs2022_win-64 19.44.35207 ha74f236_26
    - vs_win-64 2022.14 ha74f236_26
    - vswhere 3.1.7 h40126e0_1
  host:
    - libexpat 2.7.1 hac47afa_0
    - ucrt 10.0.22621.0 h57928b3_1
    - vc 14.3 h41ae7f8_26
    - vc14_runtime 14.44.35208 h818238b_26
  run:
    - libexpat 2.7.1 hac47afa_0
    - ucrt >=10.0.20348.0
    - vc >=14.3,<15
    - vc14_runtime >=14.44.35208
test: {}
about:
  home: http://expat.sourceforge.net/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Expat XML parser library in C
extra:
  feedstock-name: expat
  recipe-maintainers:
    - isuruf
    - kwilcox
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250716.4.1
  remote_url: https://github.com/conda-forge/expat-feedstock
  sha: 6178cd15d555c99dc1be92f6f3a018a7d22fa666
