# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Feb 24 08:15:01 2025
# ------------------------------------------------

package:
  name: decorator
  version: 5.2.1
source:
  sha256: 65f266143752f734b0a7cc83c46f4618af75b8c5911b00ccb61d0ac9b6da0360
  url: https://pypi.org/packages/source/d/decorator/decorator-5.2.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/decorator_1740384970518/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2025.1.31 hbcca054_0
    - ld_impl_linux-64 2.43 h712a8e2_4
    - libffi 3.4.6 h2dba641_0
    - libgcc 14.2.0 h767d61c_2
    - libgcc-ng 14.2.0 h69a702a_2
    - libgomp 14.2.0 h767d61c_2
    - liblzma 5.6.4 hb9d3cd8_0
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.49.1 hee588c1_1
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.4.1 h7b32b05_0
    - pip 25.0.1 pyh8b19718_0
    - python 3.9.21 h9c0c6dc_1_cpython
    - readline 8.2 h8c095d6_2
    - setuptools 75.8.0 pyhff2d567_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2025a h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - python >=3.9
test:
  commands:
    - pip check
  imports:
    - decorator
  requires:
    - pip
    - python 3.9.*
about:
  home: https://github.com/micheles/decorator
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: Decorators for Humans
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250224.2.1
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
  remote_url: https://github.com/conda-forge/decorator-feedstock
  sha: 7502e2f7f9a6edbb3ed2576eed0e1dbd71278482
