# This file created by conda-build 25.5.0
# ------------------------------------------------

package:
  name: sqlite
  version: 3.50.3
source:
  url: https://www.sqlite.org/2025/sqlite-autoconf-3500300.tar.gz
  sha256: ec5496cdffbc2a4adb59317fd2bf0e582bf0e6acd8f4aae7e97bc723ddba7233
build:
  run_exports:
    - libsqlite >=3.50.3,<4.0a0
  number: 1
  string: hdb435a2_1
requirements:
  build:
    - vs2022_win-64 19.44.35207 ha74f236_30
    - vs_win-64 2022.14 ha74f236_30
    - vswhere 3.1.7 h40126e0_1
  run:
    - libsqlite 3.50.3 hf5d6505_1
    - ucrt >=10.0.20348.0
    - vc >=14.3,<15
    - vc14_runtime >=14.44.35208
  host:
    - ucrt 10.0.22621.0 h57928b3_1
    - vc 14.3 h2b53caa_30
    - vc14_runtime 14.44.35208 h818238b_30
test:
  commands:
    - sqlite3 --version
    - echo PRAGMA compile_options; | sqlite3
about:
  home: http://www.sqlite.org/
  license: blessing
  license_url: http://www.sqlite.org/copyright.html
  summary: Implements a self-contained, zero-configuration, SQL database engine
  description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

    public-domain, SQL database engine.It is the most used database engine

    in the world.

    '
  doc_url: http://www.sqlite.org/docs.html
  doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
  dev_url: https://github.com/mackyle/sqlite
extra:
  recipe-maintainers:
    - flaviomartins
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250723.1.1
  remote_url: https://github.com/conda-forge/sqlite-feedstock
  sha: b64dc1052e960a69eb9504ca42c4fed4ff231f42
