# This file created by conda-build 3.21.6
# meta.yaml template originally from:
# C:\Users\builder\cvarlack\aggregate\pywin32-feedstock\recipe, last modified Tue Nov 16 10:59:28 2021
# ------------------------------------------------

package:
  name: pywin32
  version: '302'
source:
  patches:
    - 0003-remove-PATH-pth-hack.patch
    - disable_exchange_modules.patch
  sha256: 47fd53c0561ff3019043e86880597aacbd736910d8add485117d8ad055441927
  url: https://github.com/mhammond/pywin32/archive/b302.tar.gz
build:
  number: '1'
  string: py37h827c3e9_1
requirements:
  build:
    - m2-gcc-libs 5.3.0 4
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - vs2019_win-64 19.27.29111 ha89c4d3_2
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2021.10.26 haa95532_2
    - certifi 2021.10.8 py37haa95532_0
    - openssl 1.1.1l h2bbff1b_0
    - pip 21.2.4 py37haa95532_0
    - python 3.7.11 h6244533_0
    - setuptools 58.0.4 py37haa95532_0
    - sqlite 3.36.0 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.0 pyhd3eb1b0_1
    - wincertstore 0.2 py37haa95532_2
  run:
    - python >=3.7,<3.8.0a0
    - vc >=14.2,<15.0a0
    - vs2015_runtime >=14.27.29016,<15.0a0
about:
  description: 'A set of extension modules that provides access to many of the Windows
    API functions.

    '
  dev_url: https://github.com/mhammond/pywin32
  home: https://github.com/mhammond/pywin32
  license: PSF-2.0
  license_file: Pythonwin/License.txt
  summary: Python extensions for Windows
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - carlodri
    - mingwandroid
    - nicoddemus
