# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Dec  4 08:26:37 2024
# ------------------------------------------------

package:
  name: jedi
  version: 0.19.2
source:
  sha256: 4770dc3de41bde3966b02eb84fbcf557fb33cce26ad23da12c742fb50ecb11f0
  url: https://pypi.org/packages/source/j/jedi/jedi-0.19.2.tar.gz
build:
  noarch: python
  number: '1'
  script: /home/conda/feedstock_root/build_artifacts/jedi_1733300866624/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: pyhd8ed1ab_1
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.8.30 hbcca054_0
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.47.0 hadc24fc_1
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - openssl 3.4.0 hb9d3cd8_0
    - pip 24.3.1 pyh8b19718_0
    - python 3.9.20 h13acc7a_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 75.6.0 pyhff2d567_1
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024b hc8b5060_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - parso >=0.8.3,<0.9.0
    - python >=3.9
test:
  commands:
    - python -m pip check
  imports:
    - jedi
    - jedi.api
    - jedi.common
    - jedi.inference
    - jedi.inference.compiled
    - jedi.inference.compiled.subprocess
    - jedi.inference.gradual
    - jedi.inference.value
    - jedi.plugins
  requires:
    - pip
    - python 3.9.*
about:
  description: 'Jedi is a static analysis tool for Python that can be used in IDEs/editors.

    Its historic focus is autocompletion, but does static analysis for now as

    well. Jedi is fast and is very well tested. It understands Python on a

    deeper level than all other static analysis frameworks for Python.

    '
  dev_url: https://github.com/davidhalter/jedi/
  doc_source_url: https://github.com/davidhalter/jedi/blob/master/docs/index.rst
  doc_url: http://jedi.readthedocs.io/en/latest/
  home: https://github.com/davidhalter/jedi/
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE.txt
    - jedi/third_party/django-stubs/LICENSE.txt
    - jedi/third_party/typeshed/LICENSE
  summary: An autocompletion tool for Python that can be used for text editors.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241204.4.1
  recipe-maintainers:
    - asmeurer
    - goanpeca
    - nehaljwani
    - ocefpaf
  remote_url: https://github.com/conda-forge/jedi-feedstock
  sha: c92234483f3dbb00d5b7e29fe4c4d898feeb56b3
