CI: azure
CONDA_BUILD_SKIP_TESTS: ''
c_compiler: vs2017
channel_sources: conda-forge
channel_targets: conda-forge main
cl_version: 19.42.34433
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cross_target_platform: win-64
cxx_compiler: vs2017
extend_keys:
- pin_run_as_build
- ignore_version
- extend_keys
- ignore_build_only_deps
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
lua: '5'
numpy: '1.26'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
python: '3.12'
r_base: '3.4'
runtime_version: 14.42.34433
sha256: 1821577409C35B2B9505AC833E246376CC68A8262972100444010B57226F0940
target_platform: win-64
update_version: '12'
uuid: c7dac50a-e3e8-40f6-bbb2-9cc4e3dfcabe
vc: '14'
vcver: '14.3'
vsver: '17'
vsyear: '2022'
zip_keys:
- - vcver
  - vsyear
  - vsver
  - runtime_version
  - update_version
  - cl_version
  - uuid
  - sha256
  - cross_target_platform
