CI: azure
CONDA_BUILD_SKIP_TESTS: ''
c_compiler: vs2017
channel_sources: conda-forge
channel_targets: conda-forge main
cl_version: 19.44.35207
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cross_target_platform: win-64
cxx_compiler: vs2017
extend_keys:
- ignore_version
- ignore_build_only_deps
- extend_keys
- pin_run_as_build
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
lua: '5'
numpy: '1.26'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
python: '3.12'
r_base: '3.4'
runtime_version: 14.44.35208
sha256: D62841375B90782B1829483AC75695CCEF680A8F13E7DE569B992EF33C6CD14A
target_platform: win-64
update_version: '14'
uuid: 40b59c73-1480-4caf-ab5b-4886f176bf71
vc: '14'
vcver: '14.3'
vsver: '17'
vsyear: '2022'
zip_keys:
- - vcver
  - vsyear
  - vsver
  - runtime_version
  - update_version
  - cl_version
  - uuid
  - sha256
  - cross_target_platform
