# This file created by conda-build 25.3.1
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Mon Mar 31 15:18:25 2025
# ------------------------------------------------

package:
  name: libffi
  version: 3.4.6
source:
  patches:
    - 0001-arm64-use-a-dedicated-dylib-for-trampolines-so-it-ca.patch
    - 0002-Add-support-for-ffi_find_closure_for_code_np-on-Appl.patch
    - 0003-lower-autoconf-required-version.patch
    - 0004-Don-t-define-FFI_COMPLEX_TYPEDEF-ifndef-FFI_TARGET_H.patch
  sha256: b0dea9df23c863a7a50e825440f3ebffabd65df1497108e5d437747843895a4e
  url: https://github.com/libffi/libffi/releases/download/v3.4.6/libffi-3.4.6.tar.gz
build:
  number: '1'
  run_exports:
    - libffi >=3.4.6,<3.5.0a0
  string: h537db12_1
requirements:
  build:
    - autotools_clang_conda 0.0.12 h64bf75a_0
    - bzip2 1.0.8 h2466b09_7
    - ca-certificates 2025.1.31 h56e8100_0
    - clang 20.1.1 default_hec7ea82_0
    - clang-20 20.1.1 default_hec7ea82_0
    - clangxx 20.1.1 default_hec7ea82_0
    - cmake 4.0.0 hff78f93_0
    - krb5 1.21.3 hdf4eb48_0
    - libcurl 8.12.1 h88aaa65_0
    - libexpat 2.7.0 he0c23c2_0
    - libiconv 1.18 h135ad9c_1
    - libllvm20 20.1.1 h3089188_0
    - liblzma 5.6.4 h2466b09_0
    - libssh2 1.11.1 he619c9f_0
    - libuv 1.50.0 h2466b09_0
    - libxml2 2.13.7 he286e8c_0
    - libzlib 1.3.1 h2466b09_2
    - lld 20.1.1 hd91d51b_0
    - llvm-tools 20.1.1 h2a44499_0
    - m2-autoconf 2.69 4
    - m2-automake-wrapper 10 2
    - m2-automake1.10 1.10.3 4
    - m2-automake1.11 1.11.6 4
    - m2-automake1.12 1.12.6 4
    - m2-automake1.13 1.13.4 5
    - m2-automake1.14 1.14.1 4
    - m2-automake1.15 1.15 3
    - m2-automake1.6 1.6.3 3
    - m2-automake1.7 1.7.9 3
    - m2-automake1.8 1.8.5 4
    - m2-automake1.9 1.9.6 3
    - m2-base 1.0.0 2
    - m2-bash 4.3.042 5
    - m2-bash-completion 2.3 2
    - m2-catgets 1.1 3
    - m2-coreutils 8.25 102
    - m2-dash 0.5.8 2
    - m2-db 5.3.28 3
    - m2-diffutils 3.3 4
    - m2-file 5.25 2
    - m2-filesystem 2016.04 4
    - m2-findutils 4.6.0 2
    - m2-gawk 4.1.3 2
    - m2-gcc-libs 5.3.0 4
    - m2-gdbm 1.11 4
    - m2-gettext 0.19.7 4
    - m2-gmp 6.1.0 3
    - m2-grep 2.22 4
    - m2-gzip 1.7 2
    - m2-inetutils 1.9.2 2
    - m2-info 6.0 2
    - m2-less 481 2
    - m2-libasprintf 0.19.7 4
    - m2-libbz2 1.0.6 3
    - m2-libcatgets 1.1 3
    - m2-libcrypt 1.3 2
    - m2-libdb 5.3.28 3
    - m2-libgdbm 1.11 4
    - m2-libgettextpo 0.19.7 4
    - m2-libiconv 1.14 3
    - m2-libintl 0.19.7 4
    - m2-libltdl 2.4.6 3
    - m2-liblzma 5.2.2 2
    - m2-libpcre 8.38 2
    - m2-libreadline 6.3.008 8
    - m2-libtool 2.4.6 3
    - m2-libutil-linux 2.26.2 2
    - m2-libxml2 2.9.2 3
    - m2-m4 1.4.17 5
    - m2-make 4.1 5
    - m2-mintty 1!2.2.3 2
    - m2-mpfr 3.1.4 2
    - m2-msys2-launcher-git 0.3.28.860c495 2
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-ncurses 6.0.20160220 2
    - m2-perl 5.22.1 2
    - m2-sed 4.2.2 3
    - m2-tar 1.28 4
    - m2-texinfo 6.0 2
    - m2-tftp-hpa 5.2 2
    - m2-time 1.7 2
    - m2-ttyrec 1.0.8 2
    - m2-tzcode 2015.e 2
    - m2-unzip 6.0 3
    - m2-util-linux 2.26.2 2
    - m2-which 2.21 3
    - m2-zip 3.0 2
    - m2-zlib 1.2.8 4
    - msys2-conda-epoch 20160418 1
    - openssl 3.4.1 ha4e3fda_0
    - posix 1.0.0 2
    - ucrt 10.0.22621.0 h57928b3_1
    - vc 14.3 h2b53caa_26
    - vc14_runtime 14.42.34438 hfd919c2_26
    - vs2019_win-64 19.29.30139 h7dcff83_26
    - vs_win-64 2019.11 h7dcff83_26
    - vswhere 3.1.7 h57928b3_0
    - zstd 1.5.7 hbeecb71_2
  host:
    - ucrt 10.0.22621.0 h57928b3_1
    - vc 14.3 h2b53caa_26
    - vc14_runtime 14.42.34438 hfd919c2_26
  run:
    - ucrt >=10.0.20348.0
    - vc >=14.2,<15
    - vc14_runtime >=14.29.30139
test:
  commands:
    - if not exist %LIBRARY_PREFIX%/bin/ffi-8.dll exit /b 1
    - if not exist %LIBRARY_PREFIX%/lib/libffi.lib exit /b 1
    - if not exist %LIBRARY_PREFIX%/lib/ffi.lib exit /b 1
    - if not exist %LIBRARY_PREFIX%/include/ffi.h exit /b 1
    - if not exist %LIBRARY_PREFIX%/include/ffitarget.h exit /b 1
    - llvm-nm %LIBRARY_PREFIX%/lib/libffi.lib | grep "__imp_ffi_type_void"
  requires:
    - llvm-tools
    - m2-grep
about:
  description: 'The libffi library provides a portable, high level programming interface

    to various calling conventions. This allows a programmer to call any

    function specified by a call interface description at run-time.

    '
  dev_url: https://github.com/libffi/libffi
  doc_url: https://sourceware.org/libffi/
  home: https://sourceware.org/libffi/
  license: MIT
  license_file: LICENSE
  summary: A Portable Foreign Function Interface Library.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250331.5.1
  recipe-maintainers:
    - isuruf
    - scopatz
    - stefan-balke
  remote_url: https://github.com/conda-forge/libffi-feedstock
  sha: 1105c826e22f4eb4ef5147621f839770764a85b2
