# This file created by conda-build 25.5.0
# ------------------------------------------------

package:
  name: libsqlite
  version: 3.50.3
source:
  url: https://www.sqlite.org/2025/sqlite-autoconf-3500300.tar.gz
  sha256: ec5496cdffbc2a4adb59317fd2bf0e582bf0e6acd8f4aae7e97bc723ddba7233
build:
  run_exports:
    - libsqlite >=3.50.3,<4.0a0
  number: 0
  string: hf5d6505_0
requirements:
  build:
    - vs2022_win-64 19.44.35207 ha74f236_28
    - vs_win-64 2022.14 ha74f236_28
    - vswhere 3.1.7 h40126e0_1
  host:
    - ucrt 10.0.22621.0 h57928b3_1
    - vc 14.3 h41ae7f8_28
    - vc14_runtime 14.44.35208 h818238b_28
  run:
    - ucrt >=10.0.20348.0
    - vc >=14.3,<15
    - vc14_runtime >=14.44.35208
test:
  commands:
    - if not exist %PREFIX%\\Library\bin\sqlite3.dll exit 1
    - if not exist %PREFIX%\\Library\lib\sqlite3.lib exit 1
    - if not exist %PREFIX%\\Library\include\sqlite3.h exit 1
    - if not exist %PREFIX%\\Library\include\sqlite3ext.h exit 1
about:
  home: http://www.sqlite.org/
  license: Unlicense
  license_url: http://www.sqlite.org/copyright.html
  summary: Implements a self-contained, zero-configuration, SQL database engine
  description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

    public-domain, SQL database engine.It is the most used database engine

    in the world.

    '
  doc_url: http://www.sqlite.org/docs.html
  doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
  dev_url: https://github.com/mackyle/sqlite
extra:
  recipe-maintainers:
    - flaviomartins
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250718.1.1
  remote_url: https://github.com/conda-forge/sqlite-feedstock
  sha: 2ae3f4985454af23e83a91ba182867ee1fc9f577
