# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Dec  7 11:02:12 2024
# ------------------------------------------------

package:
  name: pure_eval
  version: 0.2.3
source:
  sha256: 5f4e983f40564c576c7c8635ae88db5956bb2229d7e9237d03b3c0b0190eaf42
  url: https://pypi.org/packages/source/p/pure_eval/pure_eval-0.2.3.tar.gz
build:
  noarch: python
  number: '1'
  script: '/home/conda/feedstock_root/build_artifacts/pure_eval_1733569405015/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps --ignore-installed -vvv '
  string: pyhd8ed1ab_1
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.8.30 hbcca054_0
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - liblzma 5.6.3 hb9d3cd8_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.47.0 hadc24fc_1
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - openssl 3.4.0 hb9d3cd8_0
    - packaging 24.2 pyhd8ed1ab_2
    - pip 24.3.1 pyh8b19718_0
    - python 3.9.21 h9c0c6dc_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 75.6.0 pyhff2d567_1
    - setuptools-scm 8.1.0 pyhd8ed1ab_1
    - setuptools_scm 8.1.0 hd8ed1ab_1
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.2.1 pyhd8ed1ab_1
    - typing-extensions 4.12.2 hd8ed1ab_1
    - typing_extensions 4.12.2 pyha770c72_1
    - tzdata 2024b hc8b5060_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - python >=3.9
test:
  commands:
    - pip check
  imports:
    - pure_eval
  requires:
    - pip
    - python 3.9.*
about:
  dev_url: http://github.com/alexmojaki/pure_eval
  doc_url: http://github.com/alexmojaki/pure_eval
  home: http://github.com/alexmojaki/pure_eval
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Safely evaluate AST nodes without side effects
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241207.1.1
  recipe-maintainers:
    - alexmojaki
  remote_url: https://github.com/conda-forge/pure_eval-feedstock
  sha: 7ac8cd4e25cb31add7f7cee23868d1b21a945d2d
