# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Dec  5 02:54:43 2024
# ------------------------------------------------

package:
  name: traitlets
  version: 5.14.3
source:
  sha256: 9ed0579d3502c94b4b3732ac120375cda96f923114522847de4b3bb98b96b6b7
  url: https://pypi.org/packages/source/t/traitlets/traitlets-5.14.3.tar.gz
build:
  noarch: python
  number: '1'
  script: /home/conda/feedstock_root/build_artifacts/traitlets_1733367359838/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: pyhd8ed1ab_1
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.8.30 hbcca054_0
    - editables 0.5 pyhd8ed1ab_1
    - hatchling 1.26.3 pypyhff2d567_0
    - importlib-metadata 8.5.0 pyha770c72_1
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - liblzma 5.6.3 hb9d3cd8_0
    - liblzma-devel 5.6.3 hb9d3cd8_0
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.47.0 hadc24fc_1
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - openssl 3.4.0 hb9d3cd8_0
    - packaging 24.2 pyhd8ed1ab_2
    - pathspec 0.12.1 pyhd8ed1ab_1
    - pip 24.3.1 pyh8b19718_0
    - pluggy 1.5.0 pyhd8ed1ab_1
    - python 3.9.20 h13acc7a_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 75.6.0 pyhff2d567_1
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.2.1 pyhd8ed1ab_1
    - trove-classifiers 2024.10.21.16 pyhd8ed1ab_1
    - tzdata 2024b hc8b5060_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - xz 5.6.3 hbcc6ac9_0
    - xz-gpl-tools 5.6.3 hbcc6ac9_0
    - xz-tools 5.6.3 hb9d3cd8_0
    - zipp 3.21.0 pyhd8ed1ab_1
  run:
    - python >=3.9
test:
  commands:
    - pip check
    - coverage run --source=traitlets --parallel --branch -m pytest -vv
    - coverage run --source=traitlets --parallel --branch -m pytest -vv --pyargs traitlets
    - coverage combine
    - coverage report --show-missing --skip-covered --fail-under=80
  imports:
    - traitlets
    - traitlets.config
  requires:
    - argcomplete >=3.0.3
    - coverage
    - pip
    - pytest >=7.0,<8.2
    - pytest-mock
    - pytest-mypy-testing
    - python 3.9.*
  source_files:
    - pyproject.toml
    - tests
about:
  dev_url: https://github.com/ipython/traitlets
  doc_url: https://traitlets.readthedocs.org
  home: https://traitlets.readthedocs.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Configuration system for Python applications
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241204.3.1
  recipe-maintainers:
    - Carreau
    - SylvainCorlay
    - blink1073
    - bollwyvl
    - davidbrochart
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
    - rmorshea
    - takluyver
    - zsailer
  remote_url: https://github.com/conda-forge/traitlets-feedstock
  sha: 9b8c031a7dd80c058d646b57de2f38b94dd15111
