# This file created by conda-build 25.5.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Jun  8 22:25:53 2025
# ------------------------------------------------

package:
  name: zipp
  version: 3.23.0
source:
  url: https://pypi.org/packages/source/z/zipp/zipp-3.23.0.tar.gz
  sha256: a07157588a12518c9d4034df3fbbee09c814741a33ff63c05fa29d26a2404166
build:
  number: '0'
  noarch: python
  script: '/home/conda/feedstock_root/build_artifacts/zipp_1749421620841/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . --no-deps --ignore-installed -vv '
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2025.4.26 hbd8a1cb_0
    - ld_impl_linux-64 2.43 h712a8e2_4
    - libexpat 2.7.0 h5888daf_0
    - libffi 3.4.6 h2dba641_1
    - libgcc 15.1.0 h767d61c_2
    - libgcc-ng 15.1.0 h69a702a_2
    - libgomp 15.1.0 h767d61c_2
    - liblzma 5.8.1 hb9d3cd8_2
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.50.1 hee588c1_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.5.0 h7b32b05_1
    - packaging 25.0 pyh29332c3_1
    - pip 25.1.1 pyh8b19718_0
    - python 3.9.23 hc30ae73_0_cpython
    - readline 8.2 h8c095d6_2
    - setuptools 80.9.0 pyhff2d567_0
    - setuptools-scm 6.4.2 pyhd8ed1ab_0
    - setuptools_scm 6.4.2 hd8ed1ab_0
    - tk 8.6.13 noxft_hd72426e_102
    - toml 0.10.2 pyhd8ed1ab_1
    - tomli 2.2.1 pyhd8ed1ab_1
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - python >=3.9
test:
  source_files:
    - tests
  requires:
    - importlib_metadata
    - jaraco.functools
    - jaraco.itertools
    - jaraco.test
    - more-itertools
    - pip
    - python 3.9.*
  imports:
    - zipp
  commands:
    - python -m unittest tests/test_path.py
    - pip check
about:
  home: https://github.com/jaraco/zipp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A pathlib-compatible Zipfile object wrapper
  doc_url: https://zipp.readthedocs.io/en/latest
  dev_url: https://github.com/jaraco/zipp
extra:
  recipe-maintainers:
    - jan-janssen
    - nehaljwani
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250608.2.1
  remote_url: https://github.com/conda-forge/zipp-feedstock
  sha: f9c8579dda7ffdd9cd5a0eceb25922f2d68f15e2
