# This file created by conda-build 25.5.0
# ------------------------------------------------

package:
  name: liblzma
  version: 5.8.1
source:
  url: https://github.com/tukaani-project/xz/releases/download/v5.8.1/xz-5.8.1.tar.gz
  sha256: 507825b599356c10dca1cd720c9d0d0c9d5400b9de300af00e4d1ea150795543
build:
  run_exports:
    - liblzma >=5.8.1,<6.0a0
  number: 2
  string: h2466b09_2
requirements:
  build:
    - cmake-no-system 4.0.2 he0c23c2_0
    - ninja 1.12.1 hc790b64_1
    - ucrt 10.0.22621.0 h57928b3_1
    - vc 14.3 h2b53caa_26
    - vc14_runtime 14.42.34438 hfd919c2_26
    - vs2019_win-64 19.29.30139 h7dcff83_26
    - vs_win-64 2019.11 h7dcff83_26
    - vswhere 3.1.7 h40126e0_1
  run_constrained:
    - xz 5.8.1.*
  host:
    - ucrt 10.0.22621.0 h57928b3_1
    - vc 14.3 h2b53caa_26
    - vc14_runtime 14.42.34438 hfd919c2_26
  run:
    - ucrt >=10.0.20348.0
    - vc >=14.2,<15
    - vc14_runtime >=14.29.30139
test:
  commands:
    - if not exist %LIBRARY_PREFIX%\bin\liblzma.dll exit 1
    - if exist %LIBRARY_PREFIX%\lib\lzma.lib exit 1
about:
  home: http://tukaani.org/xz/
  dev_url: http://git.tukaani.org/
  summary: a compression library with an API similar to that of zlib
  license: 0BSD
  license_file:
    - COPYING
    - COPYING.0BSD
extra:
  recipe-maintainers:
    - mingwandroid
    - msarahan
    - nehaljwani
    - ocefpaf
    - scopatz
    - xhochy
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250606.2.1
  remote_url: https://github.com/conda-forge/xz-feedstock
  sha: 86438a1d2bb4ba8a6e6c8cbb4add9c33b8110f64
